name: ci_cd-sb-microservicios-searchNode
on:  
  push:
    branches: [master]
    paths:
      - 'APP1\*'
  pull_request:
    branches: [master]
    paths:
      - 'APP2\*'

jobs:
  ci_cd-sb-microservicios-searchNode:
    uses: jdelcastillos/github-action-test/.github/workflows/template.yml@master
    with:
      lista: [
        {
          "variable":"FOLDER_WORK",
          "valor":"vars.FOLDER_PERSONALIZACION_SYNC",
          "archivo":"appspec.yml"
        },
        {
          "variable":"FOLDER_WORK",
          "valor":"vars.FOLDER_PERSONALIZACION_SYNC",
          "archivo":"appspec.yml"
        }
        ]
    secrets:
      IAM_ARN: ${{ secrets.AWS_ARN_ROLE_GITHUB }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}